fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "5.1.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "2.4.0"
    apt:
      repo: "puppetlabs/apt"
      ref: "6.0.0"
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
  symlinks:
    puppet_agent: "#{source_dir}"
